### ISSUE TITLE
https://biosimulators.org/standards/simulation-reports creates RunTimeError

### ISSUE THREAD

**Issue by matthiaskoenig** [biosimulators/Biosimulators#104]
**Please describe the bug**
Opening
https://biosimulators.org/standards/simulation-reports
creates a RunTimeError

**Please describe how to reproduce the bug**
Open https://biosimulators.org/standards/simulation-reports in Firefox

**How should BioSimulators have behaved**
No RunTimeError.

**Screenshots**
![image](https://user-images.githubusercontent.com/900538/104593433-febba100-566f-11eb-9b84-bab4de63466c.png)

**Environment (please complete the following information):**
Browser Firefox 84.0.2 (64-bit) on Linux Ubuntu

**Comment by jonrkarr** [comment]
Transferred to biosimulations/Biosimulations#1976
