### ISSUE TITLE
Register test simulator

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators#3]
## Instructions

Please use this issue to contribute a containerized simulation tool, contribute another version of a simulation tool, or update a version of a simulation tool. 

Instructions for containerizing simulation tools and examples are available at https://biosimulators.org/help.

After you submit this issue, we will review your simulation tool and discuss any necessary changes here. Once approved, we will add your simulation tool to the BioSimulators registry and it will be advertised on the BioSimulators web application.

## Pre-submission checklist

**Is your containerized simulation tool compliant with BioSimulators' conventions?**

- [ ] The container provides a [BioSimulators-compliant command-line interface](https://biosimulators.org/help) that supports the [COMBINE/OMEX archive](https://combinearchive.org/) and [SED-ML](https://sed-ml.org) formats
- [ ] The entrypoint of the container is set to this command-line interface
- [ ] The specifications of the simulator follow the [BioSimulators format](https://api.biosimulators.org)
- [ ] Optional, the source code for the simulation tool is publicly available
- [ ] Optional, the simulation tool is available through a software repository such as CRAN or PyPI
- [ ] Optional, examples, tutorials, and documentation for the simulation tool are publicly available
- [ ] Optional, the simulation tool is registered with [bio.tools](https://bio.tools/)
- [ ] Optional, the container uses [labels to provide BioContainers-compliant metadata](https://biosimulators.org/help)
- [ ] Optional, the container is registered with [BioContainers](https://biocontainers.pro/)

## Submission

**What is the name, version, and URL of the specifications of your simulation tool?**
Please follow the template YAML syntax below.

---
name: COPASI
version: 4.27.214
specificationsUrl: https://raw.githubusercontent.com/biosimulators/Biosimulators_COPASI/master/properties.json

---

edit another another another another another another another more more more more more more mroe more

**Comment by jonrkarr** [comment]
test comment 1

**Comment by biosimulators-daemon** [comment]
body

**Comment by biosimulators-daemon** [comment]
body2

**Comment by biosimulators-daemon** [comment]
body3

**Comment by jonrkarr** [comment]
body4

**Comment by jonrkarr** [comment]
body4

**Comment by jonrkarr** [comment]
body4

**Comment by jonrkarr** [comment]
body4

**Comment by biosimulators-daemon** [comment]
Thank you @jonrkarr for your submission to the BioSimulators registry of containerized simulation tools! We will review your submission and discuss any issues here.

**Comment by biosimulators-daemon** [comment]
The specifications of your simulator is valid!

**Comment by biosimulators-daemon** [comment]
Your containerized simulator is valid!

**Comment by biosimulators-daemon** [comment]
A member of the BioSimulators team will review your submission before final committment to the registry.

**Comment by biosimulators-daemon** [comment]
Your submission was committed to the BioSimulators registry. Thank you!

**Comment by biosimulators-daemon** [comment]
Your submission was committed to the BioSimulators registry. Thank you!

**Comment by jonrkarr** [comment]
separator

**Comment by biosimulators-daemon** [comment]
Thank you @jonrkarr for your submission to the BioSimulators registry of containerized simulation tools! We will review your submission and discuss any issues here.

**Comment by biosimulators-daemon** [comment]
The specifications of your simulator is valid!

**Comment by biosimulators-daemon** [comment]
Your containerized simulator is valid!

**Comment by biosimulators-daemon** [comment]
A member of the BioSimulators team will review your submission before final committment to the registry.

**Comment by biosimulators-daemon** [comment]
Your submission was committed to the BioSimulators registry. Thank you!

**Comment by biosimulators-daemon** [comment]
Thank you @jonrkarr for your submission to the BioSimulators registry of containerized simulation tools! We will review your submission and discuss any issues here.

**Comment by biosimulators-daemon** [comment]
The specifications of your simulator is valid!

**Comment by biosimulators-daemon** [comment]
Your containerized simulator is valid!

**Comment by biosimulators-daemon** [comment]
Thank you @jonrkarr for your submission to the BioSimulators registry of containerized simulation tools! We will review your submission and discuss any issues here.

**Comment by biosimulators-daemon** [comment]
The specifications of your simulator is valid!

**Comment by biosimulators-daemon** [comment]
Your containerized simulator is valid!

**Comment by biosimulators-daemon** [comment]
A member of the BioSimulators team will review your submission before final committment to the registry.

**Comment by biosimulators-daemon** [comment]
Your submission was committed to the BioSimulators registry. Thank you!
