### ISSUE TITLE
Resubmit VCell 7.4.0.48: 

### ISSUE THREAD

**Issue by CodeByDrescher** [biosimulators/Biosimulators#585]
### Simulation tool

id: vcell
version: 7.4.0.48
specificationsUrl: [virtualcell/vcell@7.4.0.48 biosimulators.json (download)](https://github.com/virtualcell/vcell/releases/download/7.4.0.48/biosimulators.json)
specificationsPatch:
version: 7.4.0.48
image:
url: ghcr.io/virtualcell/biosimulators_vcell:7.4.0.48
digest: "sha256:03f0e622174dfaf313a40e45be7c839aecfca252b4ddefc66dff49838b2ec23e"
validateImage: true
commitSimulator: false

### Support for BioSimulators' conventions

- [X] The simulation tool is provided as a Docker image
- [X] The `ENTRYPOINT` of the image is a [BioSimulators-compliant command-line interface](https://docs.biosimulations.org/concepts/conventions/simulator-interfaces/)
- [X] This command-line interface supports the [COMBINE/OMEX archive](https://combinearchive.org/) format
- [X] This command-line interface supports the [Simulation Experiment Description Markup Language (SED-ML)](https://combinearchive.org/) format
- [X] This command-line interface supports the [Hierarchical Data Format (HDF5)](https://www.hdfgroup.org/solutions/hdf5/)
- [X] The capabilities of the tool are described using [BioSimulators' format](https://docs.biosimulations.org/concepts/conventions/simulator-capabilities/)
- [X] The modeling frameworks supported by the tool are described using [Systems Biology Ontology (SBO)](https://github.com/EBI-BioModels/SBO/issues) terms
- [X] The algorithms supported by the tool are described using [Kinetic Simulation Algorithm Ontology (KiSAO)](https://github.com/SED-ML/KiSAO/issues/new/choose) ontology terms
- [X] The model formats supported by the tool are described using [EMBRACE Data and Methods (EDAM)](https://github.com/edamontology/edamontology/issues/new/choose) ontology terms
- [X] The licenses supported by the tool are described using [Software Package Data Exchange (SPDX)](https://tools.spdx.org/app/submit_new_license/) identifiers
- [X] The source code for the simulation tool is publicly available
- [X] The simulation tool is available through a software repository such as CRAN or PyPI
- [X] The simulation tool is registered with [bio.tools](https://bio.tools/)
- [X] The Docker image provides [Open Containers Initiative-compliant metadata](https://docs.biosimulations.org/concepts/conventions/simulator-images/)
- [X] The Docker image provides [BioContainers-compliant metadata](https://docs.biosimulations.org/concepts/conventions/simulator-images/)
- [X] The Docker image is registered with [BioContainers](https://biocontainers.pro/)

**Comment by biosimulators-daemon** [comment]
The validation/submission of your simulator failed.

```diff
- 'NoneType' object has no attribute 'get'
```


The complete log of your validation/submission job, including further information about the failure, is available for 90 days [here](https://github.com/biosimulators/Biosimulators/actions/runs/2949577711).

If you chose to validate your Docker image, the results of the validation of your image will be available shortly as a JSON file. A link to this file will be available for 90 days from the "Artifacts" section at the bottom of [this page](https://github.com/biosimulators/Biosimulators/actions/runs/2949577711).

Once you have fixed the problem, edit the first block of this issue to re-initiate this validation.

The BioSimulators Team is happy to help. Questions and feedback can be directed to the BioSimulators Team by posting comments to this issues that reference the GitHub team `@biosimulators/biosimulators` (without the backticks).

**Comment by biosimulators-daemon** [comment]
The validation/submission of your simulator failed.

```diff
- 'NoneType' object has no attribute 'get'
```


The complete log of your validation/submission job, including further information about the failure, is available for 90 days [here](https://github.com/biosimulators/Biosimulators/actions/runs/2949612083).

If you chose to validate your Docker image, the results of the validation of your image will be available shortly as a JSON file. A link to this file will be available for 90 days from the "Artifacts" section at the bottom of [this page](https://github.com/biosimulators/Biosimulators/actions/runs/2949612083).

Once you have fixed the problem, edit the first block of this issue to re-initiate this validation.

The BioSimulators Team is happy to help. Questions and feedback can be directed to the BioSimulators Team by posting comments to this issues that reference the GitHub team `@biosimulators/biosimulators` (without the backticks).

**Comment by moraru** [comment]
Issue created manually with error, superseded by https://github.com/biosimulators/Biosimulators/issues/586
