### ISSUE TITLE
[Bug]: 'Setup tmate session 3' github action doesn't stop

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators#609]
https://github.com/biosimulators/Biosimulators/actions/runs/4727422066/jobs/8388007806 has now been running for two hours with no signs of stopping, just endlessly repeating:

```
SSH: ssh 6ZvLCSfJkuV3jBgRJxLAEHseW@sfo2.tmate.io
Web shell: https://tmate.io/t/6ZvLCSfJkuV3jBgRJxLAEHseW
```

**Comment by luciansmith** [comment]
Update:  I tried running 'ssh 6ZvLCSfJkuV3jBgRJxLAEHseW@sfo2.tmate.io' from my own computer just to see what it would do, and it connected fine. I exited out of it, and then suddenly the run finished.  Which seems a bit much to be a coincidence?

**Comment by luciansmith** [comment]
This...might be desired behavior?  I'm now very confused, but hey.

**Comment by CodeByDrescher** [comment]
Hey Lucian, it is desired behavior...sort of. Tmate is a really useful tool that allows you to ssh into a github action at the point it's invoked from within. if you enter a session, then leave it, it should close. 

However, we generally want a shorter timeout than its default, so we should adjust the github action to have a shorter timeout.

**Comment by CodeByDrescher** [comment]
It's a quick little fix:

see #612
