### ISSUE TITLE
Submit VCell 7.3

### ISSUE THREAD

**Issue by vcellmike** [biosimulators/Biosimulators#94]
id: VCell
version: 7.3.0.07
specificationsUrl: https://raw.githubusercontent.com/biosimulators/Biosimulators_VCell/dev/biosimulators.json
validateImage: true
commitSimulator: true

**Comment by biosimulators-daemon** [comment]
The validation/submission of your simulator failed.

```diff
- 'NoneType' object has no attribute 'get'
```


The complete log of your validation/submission job, including further information about the failure, is available [here](https://github.com/biosimulators/Biosimulators/actions/runs/478356151).

Once you have fixed the problem, edit the first block of this issue to re-initiate this validation.

The BioSimulators Team is happy to help. Questions and feedback can be directed to the BioSimulators Team by posting comments to this issues that reference the GitHub team `@biosimulators/biosimulators` (without the backticks).

**Comment by jonrkarr** [comment]
Closing because VCell is not ready for validation.
